/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;



import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.Paint;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import model.EmpleadoModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import pojos.Empleado;



/**
 *
 * @author herre
 */
public class Bienvenida extends javax.swing.JDialog {
    
   private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Bienvenida.class.getName());

    private Empleado empleado;
    /**
     * Creates new form Bienvenida
     */
    public Bienvenida(Empleado empleado) {
        this.empleado = empleado;
        initComponents();


        //Título
        setTitle("CRM Music Shop - Bienvenida");

        //Tamaño, redimensionamiento y centrado
        setSize(1100, 750);  
        setResizable(false);  
        setLocationRelativeTo(null);

        //Icono de la ventana
        Image icon = new ImageIcon(getClass().getResource("/img/iconoApp.png")).getImage();
        setIconImage(icon);
        
        //Cargamos el gráfico con las ventas de los empleados
        cargarGraficoVentas();
        
        //Estilos de los campos
        
    }
    // =========================================
    // CONSTRUCCIÓN DE LA INTERFAZ (Sustituye a initComponents)
    // =========================================
    
    //Método para construis el gráfico con las ventas de los empleados
      private void cargarGraficoVentas() {

        //Crear Dataset del gráfico
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        //Obtenemos los empleados
        EmpleadoModel model = new EmpleadoModel();
        ArrayList<Empleado> lista = (ArrayList<Empleado>) model.getTodos();

        //Añadimos una barra por empleado
        for (Empleado emp : lista) {
            dataset.addValue(
                    emp.getMontoVentas(),   // valor de la barra
                    "Ventas",               // serie (solo una)
                    "ID " + emp.getId()     // etiqueta en el eje X
            );
        }

        //Creamos el gráfico de barras
        JFreeChart chart = ChartFactory.createBarChart(
                "Ventas por Empleado",     // título
                "Empleado",                // eje X
                "Ventas (€)",              // eje Y
                dataset,
                PlotOrientation.VERTICAL,
                false,                      // leyenda
                true,                       // tooltips
                false
        );

        //Configuramos el plot
        CategoryPlot plot = chart.getCategoryPlot();

        //Renderer personalizado:
        //Se encarga de decidir el color de cada barra justo cuando se pinta
        BarRenderer renderer = new BarRenderer() {

            @Override
            public Paint getItemPaint(int row, int column) {

                //column = posición del empleado en la lista
                double ventas = lista.get(column).getMontoVentas();

                //Color según el volumen de ventas
                if (ventas < 1000) {
                    return Color.RED;           //ventas bajas
                } else if (ventas < 2000) {
                    return Color.YELLOW;        //ventas medias
                } else {
                    return Color.GREEN;         //ventas altas
                }
            }
        };

        //Asignamos el renderer al plot
        plot.setRenderer(renderer);

        //Quitar borde negro de las barras (más limpio)
        renderer.setDrawBarOutline(false);

        //Insertamos el gráfico en el panel
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setMouseWheelEnabled(true); // zoom con la rueda

        pnGraficoVentas.removeAll();
        pnGraficoVentas.setLayout(new BorderLayout());
        pnGraficoVentas.add(chartPanel, BorderLayout.CENTER);
        pnGraficoVentas.revalidate();
        pnGraficoVentas.repaint();
    }





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblOfertas = new javax.swing.JLabel();
        lblObjetivos = new javax.swing.JLabel();
        pnGraficoVentas = new javax.swing.JPanel();
        pnGraficoProductos = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1100, 750));
        setMinimumSize(new java.awt.Dimension(1100, 750));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BIENVENIDO A MUSICALSHOP CRM");
        jLabel2.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Página de Inicio");

        lblOfertas.setText("Ofertas");

        lblObjetivos.setText("Objetivos de ventas");

        pnGraficoVentas.setLayout(new java.awt.BorderLayout());

        pnGraficoProductos.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInicio.setText("Inicio");
        jPanel1.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 131, 40));

        btnProductos.setText("Productos");
        jPanel1.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 125, 40));

        btnPedidos.setText("Pedidos");
        jPanel1.add(btnPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 125, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(pnGraficoVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnGraficoProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(159, 159, 159)
                            .addComponent(lblObjetivos, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(246, 246, 246)
                            .addComponent(lblOfertas, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(184, 184, 184)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblObjetivos, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblOfertas, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnGraficoProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                    .addComponent(pnGraficoVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnProductos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblObjetivos;
    private javax.swing.JLabel lblOfertas;
    private javax.swing.JPanel pnGraficoProductos;
    private javax.swing.JPanel pnGraficoVentas;
    // End of variables declaration//GEN-END:variables
}

