/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.PopupMenu;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import model.ProductoModel;
import model.WrapLayout;
import pojos.Empleado;
import pojos.Producto;

/**
 *
 * @author herre
 */
public class GaleriaProductos extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GaleriaProductos.class.getName());

    private Empleado empleado;
    private Producto producto;
    
    /**
     * Creates new form GaleriaProductos
     */
    public GaleriaProductos(Empleado empleado) {
        this.empleado = empleado;
        initComponents();
        
        //Título
        setTitle("CRM Music Shop - Galería Principal");

        //Tamaño, redimensionamiento y centrado
        setSize(1250, 800);  
        setResizable(false);  
        setLocationRelativeTo(null);

        //Icono de la ventana
        Image icon = new ImageIcon(getClass().getResource("/img/iconoApp.png")).getImage();
        setIconImage(icon);
        
        //Desactivamos el scroll horizontal
        scrollProductos.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollProductos.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);

        //Añadimos el layout personalizado para las cards
        pnGaleria.setLayout(new WrapLayout(FlowLayout.LEFT, 20, 20));
        
        //Método para cargar las cards en el Scroll Pane
        cargarCardsProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCabecera = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        scrollProductos = new javax.swing.JScrollPane();
        pnGaleria = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1250, 800));
        setMinimumSize(new java.awt.Dimension(1250, 800));

        pnCabecera.setBackground(new java.awt.Color(0, 153, 255));
        pnCabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInicio.setText("Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        pnCabecera.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 131, 40));

        btnProductos.setText("Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        pnCabecera.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 125, 40));

        btnPedidos.setText("Pedidos");
        pnCabecera.add(btnPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 125, 40));

        pnGaleria.setMaximumSize(null);
        pnGaleria.setLayout(new java.awt.GridLayout(0, 4, 20, 20));
        scrollProductos.setViewportView(pnGaleria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollProductos)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        GaleriaProductos galeria = new GaleriaProductos(empleado);
        galeria.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        Principal bienvenida = new Principal(empleado);
        bienvenida.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnInicioActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnProductos;
    private javax.swing.JPanel pnCabecera;
    private javax.swing.JPanel pnGaleria;
    private javax.swing.JScrollPane scrollProductos;
    // End of variables declaration//GEN-END:variables

    private void cargarCardsProductos() {
        pnGaleria.removeAll();

        // Obtener productos del modelo
        ProductoModel pm = ProductoModel.getInstance();
        List<Producto> lista = pm.getTodos();

        for (Producto p : lista) {
            pnGaleria.add(crearCardProducto(p));
        }

        pnGaleria.revalidate();
        pnGaleria.repaint();
    }
    
    //Método para crear las cards de nuestra galería
    private JPanel crearCardProducto(Producto p) {

        //Panel principal de la card
        JPanel card = new JPanel(); 
        card.setLayout(new BorderLayout());                                         //Layout principal
        card.setPreferredSize(new Dimension(250, 320));                             //Tamaño de card
        card.setBackground(Color.WHITE);                                            //Fondo
        card.setBorder(BorderFactory.createLineBorder(new Color(200, 200, 200)));   //Borde

        JLabel lblImg = new JLabel();                                               //Label para la imagen
        lblImg.setHorizontalAlignment(SwingConstants.CENTER);                       //Centrado horizontal

        //Cargamos y escalamos los iconos
        ImageIcon icon = new ImageIcon(getClass().getResource(p.getRutaImagen()));
        Image img = icon.getImage().getScaledInstance(200, -1, Image.SCALE_SMOOTH); 
        lblImg.setIcon(new ImageIcon(img));             //Asignamos el icono

        //Nombre del producto
        JLabel lblNombre = new JLabel(p.getNombre());
        lblNombre.setHorizontalAlignment(SwingConstants.CENTER); 
        lblNombre.setFont(new Font("Segoe UI", Font.BOLD, 14)); 

        //Precio del producto
        JLabel lblPrecio = new JLabel(p.getPrecio() + " €"); 
        lblPrecio.setHorizontalAlignment(SwingConstants.CENTER); 
        lblPrecio.setFont(new Font("Segoe UI", Font.PLAIN, 13));

        //Listener del botón
        JButton btnDetalles = new JButton("Ver detalles"); 
        btnDetalles.addActionListener(e -> abrirDetallesProducto(p)); 
        
        //Distribución del panel
        JPanel info = new JPanel();                     //Panel inferior
        info.setLayout(new GridLayout(3, 1));           //Distribución vertical
        info.add(lblNombre);                            //Añadimos nombre
        info.add(lblPrecio);                            //Añadimos precio
        info.add(btnDetalles);                          //Añadimos botón

        card.add(lblImg, BorderLayout.NORTH);           //Añadimos imagen
        card.add(info, BorderLayout.CENTER);            //Añadimos panel inferior

        return card; 
    }


    private void abrirDetallesProducto(Producto p) {
        System.out.println("Abrir detalles de: " + p.getNombre()); 
        Detalles ventana = new Detalles(null, true, empleado, p);       //Pasamos tanto el producto seleccionado como el empleado para registrar la venta
        ventana.setVisible(true);
    }
}
