/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.PopupMenu;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import model.ProductoModel;
import model.WrapLayout;
import pojos.Empleado;
import pojos.Producto;

/**
 *
 * @author herre
 */
public class GaleriaProductos extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GaleriaProductos.class.getName());

    private Empleado empleado;
    private Producto producto;
    
    /**
     * Creates new form GaleriaProductos
     */
    public GaleriaProductos(Empleado empleado) {
        this.empleado = empleado;
        initComponents();
        
        //Título
        setTitle("CRM Music Shop - Galería Principal");

        //Tamaño, redimensionamiento y centrado
        setSize(1250, 800);  
        setResizable(false);  
        setLocationRelativeTo(null);

                        FlatLightLaf.setup();   
        UIManager.put("Panel.background", Color.WHITE); // fondo blanco
        UIManager.put("Button.arc", 30); // redondeo solo para botones
       

        //Icono de la ventana
        Image icon = new ImageIcon(getClass().getResource("/img/iconoApp.png")).getImage();
        setIconImage(icon);
        
                lblTitulo.putClientProperty(FlatClientProperties.STYLE, 
    "arc: 20;" +                // Redondeo de esquinas
    "background: #ffffff;" +    // Color de fondo específico
    "border: 1,1,1,1, #cccccc, 1, 20" // Un borde sutil (opcional)
);
        
        //Desactivamos el scroll horizontal
        scrollProductos.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollProductos.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);

        //Añadimos el layout personalizado para las cards
        pnGaleria.setLayout(new WrapLayout(FlowLayout.LEFT, 20, 20));
        
        //Método para cargar las cards en el Scroll Pane
        cargarCardsProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        scrollProductos = new javax.swing.JScrollPane();
        pnGaleria = new javax.swing.JPanel();
        pnCabecera = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1250, 800));
        setMinimumSize(new java.awt.Dimension(1250, 800));

        pnGaleria.setBackground(new java.awt.Color(255, 255, 255));
        pnGaleria.setMaximumSize(null);
        pnGaleria.setLayout(new java.awt.GridLayout(0, 4, 20, 20));
        scrollProductos.setViewportView(pnGaleria);

        pnCabecera.setBackground(new java.awt.Color(255, 255, 255));
        pnCabecera.setForeground(new java.awt.Color(50, 112, 236));
        pnCabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInicio.setText("Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        pnCabecera.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 60, 20));

        btnProductos.setText("Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        pnCabecera.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 110, 20));

        btnPedidos.setText("Pedidos");
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });
        pnCabecera.add(btnPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 100, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoApp 2.png"))); // NOI18N
        pnCabecera.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 40));
        pnCabecera.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("          PRODUCTOS");
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollProductos)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(489, 489, 489)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(558, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(scrollProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        Principal bienvenida = new Principal(empleado);
        bienvenida.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        GaleriaProductos galeria = new GaleriaProductos(empleado);
        galeria.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        // TODO add your handling code here:
              Pedidos p = new Pedidos(null , true,empleado);
        p.setVisible(true);
        dispose();
                    
    }//GEN-LAST:event_btnPedidosActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnCabecera;
    private javax.swing.JPanel pnGaleria;
    private javax.swing.JScrollPane scrollProductos;
    // End of variables declaration//GEN-END:variables

    private void cargarCardsProductos() {
        pnGaleria.removeAll();

        // Obtener productos del modelo
        ProductoModel pm = ProductoModel.getInstance();
        List<Producto> lista = pm.getTodos();

        for (Producto p : lista) {
            pnGaleria.add(crearCardProducto(p));
        }

        pnGaleria.revalidate();
        pnGaleria.repaint();
    }
    
    //Método para crear las cards de nuestra galería
    private JPanel crearCardProducto(Producto p) {

        //Panel principal de la card
        JPanel card = new JPanel(); 
        card.setLayout(new BorderLayout());                                         //Layout principal
        card.setPreferredSize(new Dimension(250, 320));                             //Tamaño de card
        card.setBackground(Color.WHITE);                                            //Fondo
        card.setBorder(BorderFactory.createLineBorder(new Color(200, 200, 200)));   //Borde

        JLabel lblImg = new JLabel();                                               //Label para la imagen
        lblImg.setHorizontalAlignment(SwingConstants.CENTER);                       //Centrado horizontal

        //Cargamos y escalamos los iconos
        ImageIcon icon = new ImageIcon(getClass().getResource(p.getRutaImagen()));
        Image img = icon.getImage().getScaledInstance(200, -1, Image.SCALE_SMOOTH); 
        lblImg.setIcon(new ImageIcon(img));             //Asignamos el icono

        //Nombre del producto
        JLabel lblNombre = new JLabel(p.getNombre());
        lblNombre.setHorizontalAlignment(SwingConstants.CENTER); 
        lblNombre.setFont(new Font("Segoe UI", Font.BOLD, 14)); 

        //Precio del producto
        JLabel lblPrecio = new JLabel(p.getPrecio() + " €"); 
        lblPrecio.setHorizontalAlignment(SwingConstants.CENTER); 
        lblPrecio.setFont(new Font("Segoe UI", Font.PLAIN, 13));

        //Listener del botón
        JButton btnDetalles = new JButton("Ver detalles"); 
        btnDetalles.addActionListener(e -> abrirDetallesProducto(p)); 
        
        //Distribución del panel
        JPanel info = new JPanel();                     //Panel inferior
        info.setLayout(new GridLayout(3, 1));           //Distribución vertical
        info.add(lblNombre);                            //Añadimos nombre
        info.add(lblPrecio);                            //Añadimos precio
        info.add(btnDetalles);                          //Añadimos botón

        card.add(lblImg, BorderLayout.NORTH);           //Añadimos imagen
        card.add(info, BorderLayout.CENTER);            //Añadimos panel inferior

        return card; 
    }


    private void abrirDetallesProducto(Producto p) {
        System.out.println("Abrir detalles de: " + p.getNombre()); 
        Detalles ventana = new Detalles(null, true, empleado, p);       //Pasamos tanto el producto seleccionado como el empleado para registrar la venta
        ventana.setVisible(true);
    }
}
