/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import pojos.Pedido;
import pojos.Producto;

/**
 *
 * @author diego
 */
public class VerPedido extends javax.swing.JDialog {
    
    private Pedido pedido;
    private DefaultTableModel tablaModelo;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VerPedido.class.getName());

// Modificamos el constructor para recibir el objeto Pedido
    public VerPedido(java.awt.Frame parent, boolean modal, Pedido pedido) {
        super(parent, modal);
        this.pedido = pedido;
        initComponents();
        
        setTitle("Consulta de Pedido #" + pedido.getId());
        setSize(800, 600);
        setLocationRelativeTo(null);
        
        configurarTabla();
        cargarDatos();
    }
    
    private void configurarTabla() {
        tablaModelo = new DefaultTableModel();
        tablaModelo.addColumn("Producto");
        tablaModelo.addColumn("Categoría");
        tablaModelo.addColumn("Precio");
        tblDetalles.setModel(tablaModelo); // Asegúrate de que tu tabla se llame tblDetalles
        tblDetalles.setEnabled(false); // Deshabilitar edición
    }

    private void cargarDatos() {
        // 1. Cargar etiquetas (Asegúrate de tener estos JLabels en tu diseño)
        lblId.setText("Pedido Nº: " + pedido.getId());
        lblCliente.setText("Cliente: " + pedido.getCliente().getNombreCompleto());
        lblEstado.setText("Estado: " + pedido.getEstado().toString());
        
        // Formatear fecha bonita
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        lblFecha.setText("Fecha: " + pedido.getFecha().format(formatter));
        
        lblTotal.setText(String.format("TOTAL: %.2f €", pedido.getPrecioTotal()));

        // 2. Cargar la tabla de productos
        tablaModelo.setRowCount(0);
        List<Producto> productos = pedido.getProductos();
        
        for (Producto p : productos) {
            Object[] fila = {
                p.getNombre(),
                p.getCategoria(),
                p.getPrecio() + " €"
            };
            tablaModelo.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalles = new javax.swing.JTable();
        lblId = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDetalles);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 530, 288));

        lblId.setText("jLabel2");
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 81, -1));

        lblCliente.setText("jLabel3");
        getContentPane().add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 57, -1));

        lblEstado.setText("jLabel5");
        getContentPane().add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 61, -1));

        lblFecha.setText("jLabel6");
        getContentPane().add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 61, -1));

        jLabel3.setText("TOTAL :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 62, -1));

        lblTotal.setText("jLabel3");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 441, 66, -1));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CERRAR");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 137, 45));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblDetalles;
    // End of variables declaration//GEN-END:variables
}
